name:                fractal
version:             0.1.0.0
github:              "githubuser/fractal"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fractal#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1.13
- pretty-simple >= 2.2.0.1
- containers >= 0.6.0.1
- unordered-containers >= 0.2.10.0
- mtl

library:
  source-dirs: src

executables:
  fractal-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fractal

tests:
  fractal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fractal
